Repository rdkcentral/rdkv-halif-test-tvsettings, pull requests merged in 2024-09, with the labels that each got.

#32 L1 profile update issue fixes
  profiles/sink/Sink_4K_TvSettings.yaml
  src/test_l1_tvSettings.c
Labels: bug

#30 HDR Game mode support
  docs/pages/tv-settings_L2_Low_Level_Test_Spec.md
  profiles/sink/Sink_4K_TvSettings.yaml
Labels: NewAPI

#33 issue29 l1 l2 get ldim zone short circuit status
  docs/pages/tv-settings_High_Level_Test_Spec.md
  docs/pages/tv-settings_L2_Low_Level_Test_Spec.md
  profiles/sink/Sink_4K_TvSettings.yaml
  skeletons/src/tvSettings.c
  src/test_l1_tvSettings.c
  src/test_l2_tvSettings.c
Labels: enhancement, NewAPI
